UBIDOTS_TOKEN = "BBUS-4p3JS6lOPE6pouh8uHFWg3CjWkBm7B"
GEMINI_API_KEY = "AIzaSyA0oMnjrOjkXn58B9I1LR5D7ViH39mAjvE"
DEVICE_LABEL = "esp32"
VARIABLE_CAMERA = "camera"
VARIABLE_LIGHT = "lamp"
VARIABLE_COUNT = "people"
VARIABLE_AC = "power"
VARIABLE_TEMPERATURE = "temperature"
VARIABLE_DHT11 = "suhu"
BROKER = "industrial.api.ubidots.com"
PORT = 1883